### PR TITLE
footer repositioned when error appears

### PR DESCRIPTION
**Pull request by alexalala**
https://trello.com/c/VOj0gp9y/364-bug-footer-clips-login-button-and-main-content-on-small-screen-sizes-iphone-5-and-6

🐩

### CODE REVIEW

**Review by katjam — COMMENTED** [review]
Seems a bit round-a-bout... I'd prefer a css fix rather than adding a class in this way - but if @steph thinks it is good to go this way because there is no simple answer. OK by me.

**Review by katjam — APPROVED** [review]
OK :shamrock:

**Review by gingerbreadpup — CHANGES_REQUESTED** [review]
You can do this without the js - I made a PR here just so you can see the changes I made in one place - you can close that one whenever.

https://github.com/neontribe/ARCVMarket/pull/147

**Review by katjam — CHANGES_REQUESTED** [review]
Let's ditch this one?

**Pull request closed without merging**
