### PR TITLE
0.1/webpack simple

### PR DESCRIPTION
**Pull request by katjam**
This will be an easier starting point for a quick pre-alpha prototype.

Next steps adding CI, sass and tests. I think Sass is already there - just needs a file to read from.

### CODE REVIEW

**Comment by katjam** [comment]
Sass appears to be working... now to add tests.

**Comment by gingerbreadpup** [comment]
But does the sass file compile into a css file?

**Comment by katjam** [comment]
@gingerbreadpup It makes pink text in the output of npm run dev - so 'I guess so' but not actually looked at the dist it outputs.

**Comment by katjam** [comment]
hmm looks like the build files are: build.js  build.js.map  logo.png

So unless the css is bundled into the .js then no - it does not (but I am sure we can fix it)

**Review by gingerbreadpup — APPROVED** [review]

**Pull request merged**
