### PR TITLE
Add travis config

### PR DESCRIPTION
**Pull request by katjam**
Does this look better?

### CODE REVIEW

**Review by charlesstrange2 — COMMENTED** [review]
Ok, so this just builds then maps /dist as a webroot for github pages?

Note, we don't have any vendor stuff and i don't *think* 'npm run build' does an 'npm install'

**Comment by katjam** [comment]
I think it will npm install by default - but we will see when it runs. It will also run the tests before the build and fail if they fail.

**Comment by katjam** [comment]
Just kicked one off... let's see.

**Comment by charlesstrange2** [comment]
ooh! it does travis messages! :-)

**Pull request closed without merging**
