### PR TITLE
Check for recVouchers before getting length

### PR DESCRIPTION
**Pull request by katjam**

### CODE REVIEW

**Comment by gingerbreadpup** [comment]
yay, thanks.
:shipit:

**Comment by katjam** [comment]
Can you official approve too - before I merge in?

**Review by gingerbreadpup — APPROVED** [review]

**Review by charlesstrange2 — APPROVED** [review]
:shipit: though i'm still suspicious as to why it doesn't exist when page is rendered.

**Comment by katjam** [comment]
It does exist, just not right at the start. Otherwise you would not have been getting the value at all before I fixed it. That `if` must be running twice.

**Comment by charlesstrange2** [comment]
And yet, in store, it's defined as an empty array... very odd.

**Comment by katjam** [comment]
Empty = without the [0] item, right?

**Comment by charlesstrange2** [comment]
that's a good point! because Vue does odd things when binding a variable!
Mind at rest now.

**Pull request merged**
