### PR TITLE
favicons added

### PR DESCRIPTION
**Pull request by alexalala**
https://trello.com/c/CLrIT7id/276-make-the-favicons-work

🦑

### CODE REVIEW

**Comment by katjam** [comment]
does vue magic up the .ico file from the .pngs?

**Review by katjam — APPROVED** [review]
Spotted the .ico now. :lollipop: 
Ship it!!

**Review by charlesstrange2 — COMMENTED** [review]
Make sure they ICO and PNG files get built to the dist directory on "npm run bulld"; if they dont' wack em in the "assets", or twiddle webpack (oh, joy!) to inlcude them.

**Review by charlesstrange2 — CHANGES_REQUESTED** [review]
Needs webpacking

**Comment by alexalala** [comment]
@katjam @charlesstrange2 Further review would be great when you've got a second please! 😄

**Review by charlesstrange2 — APPROVED** [review]
:guitar:

**Pull request merged**
