### PR TITLE
Accessibility fixes

### PR DESCRIPTION
**Pull request by gingerbreadpup**
Passes the accessibility checks on WAVE and Chrome Lighthouse now. Tried to find a better way to solve the problem and couldn't - but this way seems to be accepted as an okay way of doing it, even if it's not ideal - so hopefully this will be sufficient for now. :grimacing:

### CODE REVIEW

**Review by charlesstrange2 — APPROVED** [review]
The whole "hidden offscreen" thing smells a bit. Card for improvement

**Comment by katjam** [comment]
@charlesstrange2 Hidden offscreen is a common and acceptable way of hiding stuff. (As far as I know)

**Review by katjam — APPROVED** [review]

**Comment by charlesstrange2** [comment]
Yes, explored that with steph; make me a little bit sad, but it works, and
passes the accessibility check to get me my 100% in Lighthouse. :-)

**Comment by katjam** [comment]
I've seen it done that way by many many people including Matt and Heydon -
so it can't be too terrible.

**Pull request merged**
